version: '3.8'

services:

  wordpress:
    container_name: wp
    depends_on:
      - db
    image: docker.io/maksymblinov/custom_wp:v5
    ports:
      - 80:80
    volumes:
      - db_data:/var/lib/mysql
 
    networks:
      - my_network

  db:
    container_name: db
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 1-qwerty
      MYSQL_DATABASE: real_database_name
      MYSQL_USER: admin-db
      MYSQL_PASSWORD: 1234
    restart: always     
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 9906:3306
    networks:
      - my_network    

  init-db:
    image: mysql
    command: /init_db.sh
    environment:
      MYSQL_ROOT_PASSWORD: 1-qwerty
      MYSQL_DATABASE: real_database_name
      MYSQL_USER: admin-db
      MYSQL_PASSWORD: 1234
    volumes:
      - ./init_db.sh:/init_db.sh
    depends_on:
      db:
        condition: service_started
    networks:
      - my_network   



  init-cli:
    image: wordpress:cli
    restart: "on-failure:30"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin-db
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: real_database_name
    volumes:
      - ./init_cli.sh:/init_cli.sh
    volumes_from:
      - wordpress
    depends_on:
      db:
        condition: service_started
      wordpress:
        condition: service_started
    command: /init_cli.sh  
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
   driver: bridge  